FROM node:16.17.1-buster as base
WORKDIR /nest

COPY package*.json /nest
RUN npm ci

FROM base as source
RUN npm install -g source-map-support
COPY . .

FROM source as backend
RUN npm run build backend
CMD ["sh", "-c", "node -r source-map-support/register dist/backend/main.js"]