apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  # DATABASE
  DATABASE_HOST: {{ .Values.database.host | toString | quote }}
  DATABASE_PORT: {{ .Values.database.port | toString | quote }}
  DATABASE_DB: {{ .Values.database.database | toString | quote }}
  DATABASE_LOGGING: {{ .Values.database.logging | toString | quote }}
