apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DATABASE_USERNAME: {{ .Values.database.username | toString | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | toString | b64enc | quote }}
